"""Types for the SDK operations consumed by this application."""

from datetime import datetime, tzinfo
from typing import Literal, Self

import aiohttp
from pydantic.v1 import BaseModel

API_BASE: str
BOARDS: tuple[str, ...]

def parse_url(url: str) -> tuple[bool, str, int]: ...

class Api2chError(Exception):
    code: int
    reason: str
    def __init__(self, code: int, reason: str) -> None: ...

class File(BaseModel):
    name: str
    path: str
    size: int
    @property
    def size_bytes(self) -> int: ...
    @property
    def size_string(self) -> str: ...
    @property
    def original_name(self) -> str: ...
    def url(self) -> str: ...

class Post(BaseModel):
    files: list[File]
    @property
    def header(self) -> str: ...
    @property
    def body(self) -> str: ...
    @property
    def post_id(self) -> int: ...
    def dt(self, tz: tzinfo | None = None) -> datetime: ...
    def url(self, board: str) -> str: ...

class ThreadWithStats(BaseModel):
    posts_count: int
    views: int
    @property
    def header(self) -> str: ...
    def url(self, board: str) -> str: ...

class ResponseThreads(BaseModel):
    board: str
    def sorted_by_views(self, reverse: bool = True) -> list[ThreadWithStats]: ...

class ResponseThread(BaseModel):
    board: str
    enable_subject: bool
    @property
    def posts(self) -> list[Post]: ...

class Api2chAsync:
    api_base: str
    def __init__(self, raw_results: Literal[False] = False) -> None: ...
    @property
    def session(self) -> aiohttp.ClientSession: ...
    def set_api_base(self, api_base: str) -> Self: ...
    def reset_api_base(self) -> Self: ...
    async def close(self) -> None: ...
    async def threads(self, board: str) -> ResponseThreads: ...
    async def thread(self, board: str, thread: str | int) -> ResponseThread: ...
