"""Typed persistence operations shared by the database adapters."""

from datetime import datetime
from typing import Protocol

from pydantic import JsonValue

from common.db.models import (
    ArchivedUpdate,
    ChatObservation,
    ChatRecord,
    DirectoryCreate,
    DirectoryPatch,
    DirectoryRecord,
    UsageStats,
    VkPatch,
    VkSubscription,
)


class BotRepository(Protocol):
    async def check(self) -> None: ...
    async def close(self) -> None: ...
    async def ensure_chat(self, chat: ChatObservation) -> ChatRecord: ...
    async def get_chat(self, chat_id: int) -> ChatRecord | None: ...
    async def load_settings(self, chat: ChatObservation) -> dict[str, JsonValue]: ...
    async def patch_settings(self, chat_id: int, changes: dict[str, JsonValue]) -> dict[str, JsonValue]: ...
    async def archive_update(self, update: ArchivedUpdate) -> None: ...
    async def statistics(self, since: datetime) -> UsageStats: ...
    async def list_directory(self) -> list[DirectoryRecord]: ...
    async def get_directory(self, chat_id: int) -> DirectoryRecord | None: ...
    async def create_directory(self, entry: DirectoryCreate) -> DirectoryRecord: ...
    async def patch_directory(self, chat_id: int, changes: DirectoryPatch) -> DirectoryRecord | None: ...
    async def delete_directory(self, chat_id: int) -> bool: ...
    async def list_vk_subscriptions(self) -> list[VkSubscription]: ...
    async def upsert_vk_subscription(self, owner_id: int, chat_id: int, changes: VkPatch) -> VkSubscription: ...
    async def advance_vk_cursor(self, owner_id: int, chat_id: int, last_post_id: int) -> None: ...
